name: Test branches and PRs

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  oauth2-proxy-config-downloader:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
      checks: write
      issues: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: '^1.18.0'

      - run: go test ./...
        working-directory: proxy-auth-config-downloader
